//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryCo.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSize
    {
        public ItemSize()
        {
            this.ItemPriceDetails = new HashSet<ItemPriceDetail>();
        }
    
        public int TypeId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string SizeName { get; set; }
        public string SizeName_Ar { get; set; }
    
        public virtual ICollection<ItemPriceDetail> ItemPriceDetails { get; set; }
    }
}
