//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryCo.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainCategory
    {
        public MainCategory()
        {
            this.SubCategories = new HashSet<SubCategory>();
        }
    
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public string CategoryName_Ar { get; set; }
        public string Description_Ar { get; set; }
        public string Images { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiicationDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<SubCategory> SubCategories { get; set; }
    }
}
