//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryCo.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRating
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> OrderRating1 { get; set; }
        public string OrderComment { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<decimal> DriverRating { get; set; }
        public string DriverComment { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
