//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryCo.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public int promotionId { get; set; }
        public string promotionCode { get; set; }
        public Nullable<int> percentage { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<bool> status { get; set; }
        public string Image { get; set; }
        public string StartDate { get; set; }
        public string ExpireDate { get; set; }
        public string StartTime { get; set; }
        public string ExpireTime { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string PromoTitle_En { get; set; }
        public string PromoTitle_Ar { get; set; }
        public string Desc_En { get; set; }
        public string Desc_Ar { get; set; }
        public string StoreID { get; set; }
        public string Additionals { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> PromoType { get; set; }
        public Nullable<int> Limit { get; set; }
        public string Category { get; set; }
        public Nullable<int> ItemPrice { get; set; }
    }
}
