//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryCo.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PushNotificationCustomer
    {
        public int PID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string DeviceToken { get; set; }
        public string PushMessage { get; set; }
        public Nullable<int> PushNotificationType { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<long> OrderId { get; set; }
        public string BrowserTokens { get; set; }
        public string AwsARNS { get; set; }
        public Nullable<int> DeliveryType { get; set; }
        public string Message_En { get; set; }
        public string Message_Ar { get; set; }
        public Nullable<int> PushType { get; set; }
        public Nullable<System.DateTime> Readon { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public string TopicARN { get; set; }
        public Nullable<System.DateTime> PNexpiryTime { get; set; }
        public string BrowserToken { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<long> DeletedBy { get; set; }
    
        public virtual Registration Registration { get; set; }
    }
}
