//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryCo.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSDetail
    {
        public int SMSId { get; set; }
        public Nullable<System.DateTime> SMSDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string MobileNo { get; set; }
        public string Message { get; set; }
    
        public virtual Registration Registration { get; set; }
    }
}
