//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryCo.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreInformation
    {
        public StoreInformation()
        {
            this.OrderAssignDetails = new HashSet<OrderAssignDetail>();
            this.StoreWorkDatas = new HashSet<StoreWorkData>();
        }
    
        public int StoreId { get; set; }
        public string StoreName { get; set; }
        public string StoreCode { get; set; }
        public string StoreAddress { get; set; }
        public string StoreName_ar { get; set; }
        public string StoreAddress_ar { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<int> OGCountry { get; set; }
        public Nullable<int> OGCity { get; set; }
        public string imageURL { get; set; }
        public Nullable<bool> FamilySection { get; set; }
        public Nullable<bool> Wifi { get; set; }
        public Nullable<bool> PatioSitting { get; set; }
        public Nullable<bool> DriveThru { get; set; }
        public Nullable<bool> MeetingSpace { get; set; }
        public Nullable<bool> Hospital { get; set; }
        public Nullable<bool> University { get; set; }
        public Nullable<bool> Office { get; set; }
        public Nullable<bool> ShoppingMall { get; set; }
        public Nullable<bool> Airport { get; set; }
        public Nullable<bool> DineIn { get; set; }
        public Nullable<bool> Ladies { get; set; }
        public Nullable<bool> Neighbourhood { get; set; }
        public string Message { get; set; }
        public string Message_ar { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> DeliveryDistance { get; set; }
        public Nullable<int> DineInDistance { get; set; }
        public Nullable<bool> OnlineOrderStatus { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
        public string PreparationHours { get; set; }
        public string DeliveryTimings { get; set; }
        public string DeliveryStart { get; set; }
        public string DeliveryEnd { get; set; }
        public Nullable<decimal> MinOrderAmount { get; set; }
    
        public virtual ICollection<OrderAssignDetail> OrderAssignDetails { get; set; }
        public virtual ICollection<StoreWorkData> StoreWorkDatas { get; set; }
    }
}
