//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryCo.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreWorkData
    {
        public int StoreWorkId { get; set; }
        public int StoreId { get; set; }
        public string satST { get; set; }
        public string satET { get; set; }
        public Nullable<bool> isSatClose { get; set; }
        public string sunST { get; set; }
        public string sunET { get; set; }
        public Nullable<bool> isSunClose { get; set; }
        public string monST { get; set; }
        public string monET { get; set; }
        public Nullable<bool> isMonClose { get; set; }
        public string tueST { get; set; }
        public string tueET { get; set; }
        public Nullable<bool> isTueClose { get; set; }
        public string wedST { get; set; }
        public string wedET { get; set; }
        public Nullable<bool> isWedClose { get; set; }
        public string thuST { get; set; }
        public string thuET { get; set; }
        public Nullable<bool> isThuClose { get; set; }
        public string friST { get; set; }
        public string friET { get; set; }
        public Nullable<bool> isFriClose { get; set; }
        public Nullable<bool> is24x7 { get; set; }
        public string phone { get; set; }
    
        public virtual StoreInformation StoreInformation { get; set; }
    }
}
