//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryCo.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPromoDetail
    {
        public int ID { get; set; }
        public string UserId { get; set; }
        public Nullable<int> PromoId { get; set; }
        public Nullable<int> TotalBonus { get; set; }
        public Nullable<int> RemainingBonus { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
