//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryCo.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddressDetail
    {
        public UserAddressDetail()
        {
            this.OrderInfoes = new HashSet<OrderInfo>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string HouseNo { get; set; }
        public string LandMark { get; set; }
        public string Address { get; set; }
        public string AddressType { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string HouseName { get; set; }
    
        public virtual ICollection<OrderInfo> OrderInfoes { get; set; }
    }
}
