//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryCo.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class userPromotion
    {
        public int Id { get; set; }
        public Nullable<int> userId { get; set; }
        public string DeviceToken { get; set; }
        public string promotionCode { get; set; }
        public Nullable<int> orderId { get; set; }
        public Nullable<System.DateTime> usedDate { get; set; }
        public Nullable<decimal> BonusAmt { get; set; }
    }
}
