//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryCo.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDeviceToken
    {
        public long Id { get; set; }
        public string DeviceToken { get; set; }
        public string Source { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<bool> Subscribed { get; set; }
        public string AWSARN { get; set; }
        public string SubscriptionARN { get; set; }
    }
}
