//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryCo.Repositary.ws.jawalbsms.dll {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ws.jawalbsms.dll.ServicesSoap")]
    public interface ServicesSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        BakeryCo.Repositary.ws.jawalbsms.dll.SendSMSResponse SendSMS(BakeryCo.Repositary.ws.jawalbsms.dll.SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<BakeryCo.Repositary.ws.jawalbsms.dll.SendSMSResponse> SendSMSAsync(BakeryCo.Repositary.ws.jawalbsms.dll.SendSMSRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBalance", ReplyAction="*")]
        BakeryCo.Repositary.ws.jawalbsms.dll.GetBalanceResponse GetBalance(BakeryCo.Repositary.ws.jawalbsms.dll.GetBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<BakeryCo.Repositary.ws.jawalbsms.dll.GetBalanceResponse> GetBalanceAsync(BakeryCo.Repositary.ws.jawalbsms.dll.GetBalanceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS", Namespace="http://tempuri.org/", Order=0)]
        public BakeryCo.Repositary.ws.jawalbsms.dll.SendSMSRequestBody Body;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(BakeryCo.Repositary.ws.jawalbsms.dll.SendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Text;
        
        public SendSMSRequestBody() {
        }
        
        public SendSMSRequestBody(string username, string password, string sender, string Mobile, string Text) {
            this.username = username;
            this.password = password;
            this.sender = sender;
            this.Mobile = Mobile;
            this.Text = Text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public BakeryCo.Repositary.ws.jawalbsms.dll.SendSMSResponseBody Body;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(BakeryCo.Repositary.ws.jawalbsms.dll.SendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BakeryCo.Repositary.ws.jawalbsms.dll.ArrayOfString SendSMSResult;
        
        public SendSMSResponseBody() {
        }
        
        public SendSMSResponseBody(BakeryCo.Repositary.ws.jawalbsms.dll.ArrayOfString SendSMSResult) {
            this.SendSMSResult = SendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalance", Namespace="http://tempuri.org/", Order=0)]
        public BakeryCo.Repositary.ws.jawalbsms.dll.GetBalanceRequestBody Body;
        
        public GetBalanceRequest() {
        }
        
        public GetBalanceRequest(BakeryCo.Repositary.ws.jawalbsms.dll.GetBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetBalanceRequestBody() {
        }
        
        public GetBalanceRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public BakeryCo.Repositary.ws.jawalbsms.dll.GetBalanceResponseBody Body;
        
        public GetBalanceResponse() {
        }
        
        public GetBalanceResponse(BakeryCo.Repositary.ws.jawalbsms.dll.GetBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BakeryCo.Repositary.ws.jawalbsms.dll.ArrayOfString GetBalanceResult;
        
        public GetBalanceResponseBody() {
        }
        
        public GetBalanceResponseBody(BakeryCo.Repositary.ws.jawalbsms.dll.ArrayOfString GetBalanceResult) {
            this.GetBalanceResult = GetBalanceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicesSoapChannel : BakeryCo.Repositary.ws.jawalbsms.dll.ServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesSoapClient : System.ServiceModel.ClientBase<BakeryCo.Repositary.ws.jawalbsms.dll.ServicesSoap>, BakeryCo.Repositary.ws.jawalbsms.dll.ServicesSoap {
        
        public ServicesSoapClient() {
        }
        
        public ServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BakeryCo.Repositary.ws.jawalbsms.dll.SendSMSResponse BakeryCo.Repositary.ws.jawalbsms.dll.ServicesSoap.SendSMS(BakeryCo.Repositary.ws.jawalbsms.dll.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public BakeryCo.Repositary.ws.jawalbsms.dll.ArrayOfString SendSMS(string username, string password, string sender, string Mobile, string Text) {
            BakeryCo.Repositary.ws.jawalbsms.dll.SendSMSRequest inValue = new BakeryCo.Repositary.ws.jawalbsms.dll.SendSMSRequest();
            inValue.Body = new BakeryCo.Repositary.ws.jawalbsms.dll.SendSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.sender = sender;
            inValue.Body.Mobile = Mobile;
            inValue.Body.Text = Text;
            BakeryCo.Repositary.ws.jawalbsms.dll.SendSMSResponse retVal = ((BakeryCo.Repositary.ws.jawalbsms.dll.ServicesSoap)(this)).SendSMS(inValue);
            return retVal.Body.SendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BakeryCo.Repositary.ws.jawalbsms.dll.SendSMSResponse> BakeryCo.Repositary.ws.jawalbsms.dll.ServicesSoap.SendSMSAsync(BakeryCo.Repositary.ws.jawalbsms.dll.SendSMSRequest request) {
            return base.Channel.SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<BakeryCo.Repositary.ws.jawalbsms.dll.SendSMSResponse> SendSMSAsync(string username, string password, string sender, string Mobile, string Text) {
            BakeryCo.Repositary.ws.jawalbsms.dll.SendSMSRequest inValue = new BakeryCo.Repositary.ws.jawalbsms.dll.SendSMSRequest();
            inValue.Body = new BakeryCo.Repositary.ws.jawalbsms.dll.SendSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.sender = sender;
            inValue.Body.Mobile = Mobile;
            inValue.Body.Text = Text;
            return ((BakeryCo.Repositary.ws.jawalbsms.dll.ServicesSoap)(this)).SendSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BakeryCo.Repositary.ws.jawalbsms.dll.GetBalanceResponse BakeryCo.Repositary.ws.jawalbsms.dll.ServicesSoap.GetBalance(BakeryCo.Repositary.ws.jawalbsms.dll.GetBalanceRequest request) {
            return base.Channel.GetBalance(request);
        }
        
        public BakeryCo.Repositary.ws.jawalbsms.dll.ArrayOfString GetBalance(string username, string password) {
            BakeryCo.Repositary.ws.jawalbsms.dll.GetBalanceRequest inValue = new BakeryCo.Repositary.ws.jawalbsms.dll.GetBalanceRequest();
            inValue.Body = new BakeryCo.Repositary.ws.jawalbsms.dll.GetBalanceRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            BakeryCo.Repositary.ws.jawalbsms.dll.GetBalanceResponse retVal = ((BakeryCo.Repositary.ws.jawalbsms.dll.ServicesSoap)(this)).GetBalance(inValue);
            return retVal.Body.GetBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BakeryCo.Repositary.ws.jawalbsms.dll.GetBalanceResponse> BakeryCo.Repositary.ws.jawalbsms.dll.ServicesSoap.GetBalanceAsync(BakeryCo.Repositary.ws.jawalbsms.dll.GetBalanceRequest request) {
            return base.Channel.GetBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<BakeryCo.Repositary.ws.jawalbsms.dll.GetBalanceResponse> GetBalanceAsync(string username, string password) {
            BakeryCo.Repositary.ws.jawalbsms.dll.GetBalanceRequest inValue = new BakeryCo.Repositary.ws.jawalbsms.dll.GetBalanceRequest();
            inValue.Body = new BakeryCo.Repositary.ws.jawalbsms.dll.GetBalanceRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((BakeryCo.Repositary.ws.jawalbsms.dll.ServicesSoap)(this)).GetBalanceAsync(inValue);
        }
    }
}
